import { defineStore } from "pinia";

export const useStore = defineStore("store", {
  state: () => ({
    
    groups: ["Milks & Diaries", "Coffees & Teas", "Pet Foods", "Meats", "Vegetables", "Fruits"],

    searchboxes: [
        {
            id: 1,
            title_color: "black",
            title_size: "16px",
            title_text: "All Categories",
            left_icon: "uil uil-angle-down",
            left_icon_color: "gray",
            left_icon_size: "16px",
            placeholder: "Search for items",
            right_icon: "uil uil-search",
            right_icon_color: "gray",
            right_icon_size: "20px",
        },
    ],


    subheaders: [
        {
            id: 1,
            browse_left_icon: "uil uil-dice-four",
            browse_left_icon_color: "white",
            browse_left_icon_size: "26px",
            browse_text_color: "white",
            browse_text: "Broswe All Categories",
            browse_right_icon: "uil uil-angle-down",
            browse_right_icon_color: "white",
            browse_right_icon_size: "20px",
            right_icon: "uil uil-headphones-alt",
            right_icon_color: "black",
            right_icon_size: "40px",
            tel: "023 880 880",
            tel_color: "#3BB77E",
            tel_size: "24px",
        }
    ],

    menuitems: [
        {
            id: 1,
            first_icon: "uil uil-user",
            text: "Account",
            second_icon: "",
            first_icon_color: "black",
            text_color: "rgba(126, 126, 126, 1)",
            second_icon_color: "",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 2,
            first_icon: "uil uil-redo",
            text: "Compare",
            second_icon: "",
            first_icon_color: "black",
            text_color: "rgba(126, 126, 126, 1)",
            second_icon_color: "",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        }, {
            id: 3,
            first_icon: "uil uil-heart",
            text: "Wishlist",
            second_icon: "",
            first_icon_color: "black",
            text_color: "rgba(126, 126, 126, 1)",
            second_icon_color: "",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 4,
            first_icon: "uil uil-shopping-cart",
            text: "Cart",
            second_icon: "",
            first_icon_color: "black",
            text_color: "rgba(126, 126, 126, 1)",
            second_icon_color: "",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 5,
            first_icon: "uil uil-fire",
            text: "Hot Deals",
            second_icon: "",
            first_icon_color: "#3BB77E",
            text_color: "black",
            second_icon_color: "",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 6,
            first_icon: "",
            text: "Home",
            second_icon: "",
            first_icon_color: "#3BB77E",
            text_color: "black",
            second_icon_color: "",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 7,
            first_icon: "",
            text: "Food",
            second_icon: "uil uil-angle-down",
            first_icon_color: "",
            text_color: "black",
            second_icon_color: "black",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 8,
            first_icon: "",
            text: "Vegetables",
            second_icon: "uil uil-angle-down",
            first_icon_color: "",
            text_color: "black",
            second_icon_color: "black",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 9,
            first_icon: "",
            text: "Drinks",
            second_icon: "",
            first_icon_color: "",
            text_color: "black",
            second_icon_color: "",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 10,
            first_icon: "",
            text: "Cookies",
            second_icon: "",
            first_icon_color: "",
            text_color: "black",
            second_icon_color: "",
            first_icon_size: "24px",
            first_text_size: "16px",
            second_icon_size: "",
        },  {
            id: 11,
            first_icon: "",
            text: "Meat & Seafood",
            second_icon: "uil uil-angle-down",
            first_icon_color: "",
            text_color: "black",
            second_icon_color: "black",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },  {
            id: 12,
            first_icon: "",
            text: "Bakery",
            second_icon: "",
            first_icon_color: "",
            text_color: "black",
            second_icon_color: "",
            first_icon_size: "24px",
            text_size: "16px",
            second_icon_size: "",
        },
    
    ],

    subscribes: [
        {
            id: 1,
            image_background: new URL('../assets/images/3389452 1.png', import.meta.url),
            image_frontground: new URL('../assets/images/fresh-apples-shopping-mesh-bag-with-branch-apples-removebg 1.png', import.meta.url),
            title_letter: "Don't miss amazing grocery deals",
            title_letter_color: "#253D4E",
            desc_letter: "Sign up for the daily newsletter ",
            desc_letter_color: "rgba(126, 126, 126, 1)",
        },

    ],

    menus: [
        {
            id: 1,
            title: "Featured Categories",
            menu_color: "black",
        },  {
            id: 2,
            title: "Popular Products",
            title_color: "black",
        },
    
    ],

    categories: [
        {
            id: 1,
            group: "Milks & Diaries",
            name: "Cake & Milk",
            color: "#F2FCE4",
            amount: "14",
            image: new URL('../assets/images/cat-13 1.png', import.meta.url),
        }, {
            id: 2,
            group: "Fruits",
            name: "Peach",
            color: "#FFFCEB",
            amount: "17",
            image: new URL('../assets/images/cat-11 1.png', import.meta.url),
        }, {
            id: 3,
            group: "Fruits",
            name: "Organic Kiwi",
            color: "#ECFFEC",
            amount: "21",
            image: new URL('../assets/images/cat-12 1.png', import.meta.url),
        }, {
            id: 4,
            group: "Fruits",
            name: "Red Apple",
            color: "#FEEFEA",
            amount: "68",
            image: new URL('../assets/images/cat-9 1.png', import.meta.url),
        }, {
            id: 5,
            group: "Pet Foods",
            name: "Snack",
            color: "#FFF3EB",
            amount: "34",
            image: new URL('../assets/images/cat-3 1.png', import.meta.url),
        }, {
            id: 6,
            group: "Fruits",
            name: "Black plum",
            color: "#FFF3FF",
            amount: "25",
            image: new URL('../assets/images/cat-4 1.png', import.meta.url),
        }, {
            id: 7,
            group: "Vegetables",
            name: "Vegetables",
            color: "#F2FCE4",
            amount: "65",
            image: new URL('../assets/images/cat-1 4.png', import.meta.url),
        }, {
            id: 8,
            group: "",
            name: "Headphone",
            color: "#FFFCEB",
            amount: "33",
            image: new URL('../assets/images/cat-15 1.png', import.meta.url),
        }, {
            id: 9,
            group: "Milks & Dairies",
            name: "Cake & Milk",
            color: "#F2FCE4",
            amount: "54",
            image: new URL('../assets/images/cat-14 1.png', import.meta.url),
        }, {
            id: 10,
            group: "Fruits",
            name: "Orange",
            color: "#FFF3FF",
            amount: "63",
            image: new URL('../assets/images/cat-7 1.png', import.meta.url),
        }, ],


    promotions: [
        {
            id: 1,
            letter: "Everyday Fresh & Clean with Our Products",
            letter_color: "",
            text: "Shop Now",
            bg_color: "#F0E8D5",
            button_color: "#FFF3FF",
            button_bg_color: "#3BB77E", 
            image: new URL('../assets/images/Cms-04 1.png', import.meta.url),
        }, {
            id: 2,
            letter: "Make your Breakfast Healthy and Easy",
            letter_color: "",
            text: "Shop Now",
            bg_color: "#F3E8E8",
            button_color: "#FFF3FF",
            button_bg_color: "#3BB77E", 
            image: new URL('../assets/images/Cat-01 1.png', import.meta.url),
        }, {
            id: 3,
            letter: "The best Organic Products Online",
            letter_color: "",
            text: "Shop Now",
            bg_color: "#E7EAF3",
            button_color: "#FFF3FF",
            button_bg_color: "#FDC040", 
            image: new URL('../assets/images/Cms-03 1.png', import.meta.url),
        }, ],
      

    products: [
        {
            id: 1,
            bg_color: "white",
            inform_bg_color: "#3BB77E",
            inform_text: "-17%",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/18 1.png', import.meta.url),
        }, {
            id: 2,
            bg_color: "white",
            inform_bg_color: "#FD6E6E",
            inform_text: "Hot",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "All Natural Italian-Style Chicken Meatballs",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/1 902.png', import.meta.url),
        }, {
            id: 3,
            bg_color: "white",
            inform_bg_color: "#FDC040",
            inform_text: "Sale",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Angie's Boomchickapop Sweet & Salty Kettie Corn",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/3 389454.png', import.meta.url),
        }, {
            id: 4,
            bg_color: "white",
            inform_bg_color: "",
            inform_text: "-17%",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Foster Farm Takeout Crispy Classic Buffalo Wings",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/5 7.png', import.meta.url),
        }, {
            id: 5,
            bg_color: "white",
            inform_bg_color: "",
            inform_text: "-17%",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Blue Diamond Almonds Lightly Salted Vegetables",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/7 1.png', import.meta.url),
        }, {
            id: 6,
            bg_color: "white",
            inform_bg_color: "",
            inform_text: "-17%",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Chobani Complete Vanilla Greek Yogurt",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/8 1.png', import.meta.url),
        }, {
            id: 7,
            bg_color: "white",
            inform_bg_color: "#FDC040",
            inform_text: "Sale",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Canada Dry Ginger Ale - 2L Botle - 200ml - 400g",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/9 1.png', import.meta.url),
        }, {
            id: 8,
            bg_color: "white",
            inform_bg_color: "",
            inform_text: "-17%",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Encore Seafoods Stuffed Alaskan Salmon",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/11 1.png', import.meta.url),
        }, {
            id: 9,
            bg_color: "white",
            inform_bg_color: "",
            inform_text: "-17%",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Garton's Beer Battered Fish Fillets with soft paper",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/12 1.png', import.meta.url),
        }, {
            id: 10,
            bg_color: "white",
            inform_bg_color: "#FD6E6E",
            inform_text: "Hot",
            inform_color: "white",
            company_name: "Hodo Foods",
            company_color: "#7E7E7E",
            title: "Haagen-Dazs Caramel Cone Ice Cream Ketchup",
            title_color: "black",
            rating: "0",
            rating_color: "#7E7E7E",
            weight: "500 gram",
            weight_color: "#7E7E7E",
            discount_price: "2.51",
            discount_color: "#3BB77E",
            price_original: "3.00",
            price_color: "#7E7E7E",
            add_bg: "#DEF9EC",
            add_letter: "Add",
            add_color: "#3BB77E",
            image: new URL('../assets/images/16 1.png', import.meta.url),
        },
    ],
  }),
});
